In [1]:
from IPython.core.display import HTML
HTML(r"""
<style>
    .output-plaintext, .output-stream, .output {
        font-family: Fira Code; # Any monospaced font should work
        line-height: 2.0 !important;
    }
</style>
""")


# PyTorch Fundamentals

[Resource notebook](https://www.learnpytorch.io/00_pytorch_fundamentals/)

[Github discussions](https://github.com/mrdbourke/pytorch-deep-learning/discussions)

In [2]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())


1.13.0+cu117
True


### introduction to tensors
Creating tensors

PyTorch tensors are created using `torch.Tensor` = https://pytorch.org/docs/stable/tensors.html

In [3]:
# scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [4]:
scalar.ndim


0

In [5]:
# Get tensor back as Python int
scalar.item()


7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector


tensor([7, 7])

In [7]:
vector.ndim


1

In [8]:
vector.shape


torch.Size([2])

In [9]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim


2

In [11]:
MATRIX[1]


tensor([ 9, 10])

In [12]:
MATRIX.shape


torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim


3

In [15]:
TENSOR.shape


torch.Size([1, 3, 3])

In [16]:
TENSOR[0]


tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

TOrch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [17]:
# Create a rnadom tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor


tensor([[0.2874, 0.9108, 0.4552, 0.2291],
        [0.3675, 0.5374, 0.1342, 0.5507],
        [0.6799, 0.0223, 0.5933, 0.2401]])

In [18]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224))  # height, width, colour channels (R, G, B)

random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([3, 224, 224]), 3)

In [19]:
random_image_size_tensor


tensor([[[0.2612, 0.9934, 0.6522,  ..., 0.7192, 0.6280, 0.9629],
         [0.6357, 0.5424, 0.0672,  ..., 0.7131, 0.2234, 0.2141],
         [0.1964, 0.8421, 0.5373,  ..., 0.7324, 0.8871, 0.1406],
         ...,
         [0.9671, 0.1017, 0.4983,  ..., 0.3066, 0.9078, 0.4922],
         [0.7266, 0.3038, 0.7377,  ..., 0.0707, 0.3965, 0.1224],
         [0.6785, 0.9795, 0.5815,  ..., 0.9681, 0.3626, 0.2258]],

        [[0.8394, 0.2160, 0.8612,  ..., 0.6996, 0.7570, 0.5833],
         [0.5080, 0.3817, 0.9434,  ..., 0.7974, 0.2721, 0.6673],
         [0.7429, 0.0196, 0.3440,  ..., 0.2426, 0.8804, 0.7665],
         ...,
         [0.8445, 0.5350, 0.4243,  ..., 0.6316, 0.3255, 0.0218],
         [0.0875, 0.8465, 0.4203,  ..., 0.9893, 0.4764, 0.2100],
         [0.4455, 0.1918, 0.5174,  ..., 0.5726, 0.0476, 0.0584]],

        [[0.0358, 0.0939, 0.6347,  ..., 0.8814, 0.1087, 0.7333],
         [0.0703, 0.9916, 0.7802,  ..., 0.4855, 0.0789, 0.6790],
         [0.2271, 0.1129, 0.5218,  ..., 0.8851, 0.2803, 0.

In [20]:
torch.rand(3, 3)


tensor([[0.1250, 0.5433, 0.5546],
        [0.8907, 0.4538, 0.9566],
        [0.9446, 0.7196, 0.6634]])

### Zeros and ones


In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype


torch.float32

### Creating a range of tensors and tensors-like

In [24]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [26]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,  # what datatype is teh tensor (e.g. float32 or float16)
                               device=None,  # what device is your tensor on
                               requires_grad=False)  # whether or not to track gradients values
float_32_tensor


tensor([3., 6., 9.])

In [27]:
float_32_tensor.dtype


torch.float32

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
float_16_tensor * float_32_tensor


tensor([ 9., 36., 81.])

In [30]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor


tensor([3, 6, 9], dtype=torch.int32)

In [31]:
float_32_tensor * int_32_tensor


tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [32]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor


tensor([[0.3888, 0.5292, 0.0866, 0.7248],
        [0.2392, 0.2124, 0.7419, 0.0102],
        [0.4467, 0.6014, 0.8057, 0.1340]])

In [33]:
# Find out details about some tensor
print(some_tensor)
print(F"Datatype of tensor: {some_tensor.dtype}")
print(F"Shape of tensor: {some_tensor.shape}")
print(F"Device tensor is on: {some_tensor.device}")


tensor([[0.3888, 0.5292, 0.0866, 0.7248],
        [0.2392, 0.2124, 0.7419, 0.0102],
        [0.4467, 0.6014, 0.8057, 0.1340]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [34]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10


tensor([11, 12, 13])

In [35]:
# Multiply tensor by 10
tensor * 10


tensor([10, 20, 30])

In [36]:
# Substract 10
tensor - 10


tensor([-9, -8, -7])

In [37]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)


tensor([10, 20, 30])

In [38]:
torch.add(tensor, 10)


tensor([11, 12, 13])

### Matcix multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise 
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimesions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(3, 2) @ (2, 3)` will work
* `(2, 3) @ (3, 2)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [39]:
# Element wise multiplication
print(tensor, "*", tensor)
print(F"Equals: {tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [40]:
# Matrix multiplication
torch.matmul(tensor, tensor)


tensor(14)

In [41]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3


14

In [42]:
% % time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)


UsageError: Line magic function `%` not found.


In [43]:
% % time
torch.matmul(tensor, tensor)


UsageError: Line magic function `%` not found.


### One of the most common errors in deep learning: shape errors

In [44]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B)  # torch.mm is the same as torch.matmul (it's an alias for writing less code)


To fix our tensor shape issues, we can manipulate the shape of  our tensors using a **transpose.**

A transpose switches the axes or dimensions of a given tensor.

In [45]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [46]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [47]:
# The matrix multiplication operation works when tensor_B is transposed
print(F"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(F"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(F"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(F"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc(tensor aggregation)

In [48]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [49]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [50]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [51]:
# Find the mean - note : the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()


(tensor(46.), tensor(46.))

In [52]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Find the positional min and max

In [53]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [54]:
# Find the position in tensor that has the minimum vaule with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [55]:
x[0]

tensor(1)

In [56]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [57]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - Return a view of the input with dimensions permuted(swapped) in a certain way
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [58]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [59]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [60]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [61]:
# Changing z changes x (because a view of a  tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [62]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [63]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(F"Previous tensor: {x_reshaped}")
print(F"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(F"\nNew tensor: {x_squeezed}")
print(F"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [64]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(F"Previous target: {x_squeezed}")
print(F"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(F"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [65]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3))  # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)  # shifts axis 0->1, 1->2, 2->0

print(F"Previous shape: {x_original.shape}")
print(F"New shape: {x_permuted.shape}")  # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing(selecting datat from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [66]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [67]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [68]:
# Let's index on the middle bracket (dim=1)
x[0, 0]  # same as x[0][0]

tensor([1, 2, 3])

In [69]:
# Let's index on the most inner bracket (lart dimension)
x[0][0][0]

tensor(1)

In [70]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [71]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [72]:
# Get all values of 0 dimensions but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [73]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

## PyTorch tnesors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [74]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)  # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [75]:
# Change the value of array, what will this do to `tensor``?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [76]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [77]:
# Change the tensor, what happens to `numpy_tensor`
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [78]:
import torch

# Creeate two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.3361, 0.0087, 0.6377, 0.8980],
        [0.1686, 0.2119, 0.1448, 0.6177],
        [0.5852, 0.7836, 0.2647, 0.4558]])
tensor([[0.0167, 0.0370, 0.5006, 0.6586],
        [0.6400, 0.6554, 0.9172, 0.3301],
        [0.6783, 0.6511, 0.1629, 0.4094]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [79]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Extra resources for reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardward + PyTorch working behind the scenes to make everything hunky dory(good).

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options..., see this post for what option to get:https://bizon-tech.com/blog/best-gpu-for-deep-learning-rtx-3090-vs-rtx-3080-vs-titan-rtx-vs-rtx-2080-ti#:~:text=NVIDIA's%20RTX%203090%20is%20the,projects%20to%20the%20next%20level.
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers(CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation:https://pytorch.org/get-started/locally/

### 2. Check for GPU access with PyTorch

In [80]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code:
https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on GPU if available, else default to CPU

In [81]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [82]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensor/models on the GPU results in faster computations.

In [84]:
# Create a tensor (default on the GPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [85]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [87]:
# If tensor is on GPU, can't transform it to NumPy
# tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [88]:
# To fix the GPU tensor with NumPy issue, we can first set it to the GPU
tensor_back_on_gpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_gpu

array([1, 2, 3], dtype=int64)